# Generated by Django 2.1 on 2019-11-18 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freeboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='freeboard',
            options={'ordering': ['-created_at']},
        ),
    ]
