# Generated by Django 2.0.7 on 2019-12-07 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20191206_2229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='gallery',
            new_name='post',
        ),
    ]
