# Generated by Django 2.1.7 on 2019-12-18 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_auto_20191217_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='upload_file',
            field=models.FileField(blank=True, null=True, upload_to='upload-file'),
        ),
    ]
