# Generated by Django 2.0.7 on 2019-12-21 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_auto_20191118_1552'),
        ('notice', '0004_auto_20191207_2237'),
    ]

    operations = [
    ]
