# Generated by Django 2.0.7 on 2022-08-01 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0006_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='option',
        ),
        migrations.AddField(
            model_name='notice',
            name='is_all',
            field=models.BooleanField(default=False, verbose_name='전체 게시판 공지여부'),
        ),
        migrations.AddField(
            model_name='notice',
            name='is_fixed',
            field=models.BooleanField(default=False, verbose_name='상단 고정여부'),
        ),
    ]
