# Generated by Django 2.0.7 on 2022-07-04 10:33

from django.db import migrations, models
import django.db.models.deletion
import information.models.carousel
import information.models.church_introduce
import information.models.father_sister
import information.models.pastoral_orientation
import information.models.popup


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carousel_image', models.ImageField(blank=True, null=True, upload_to=information.models.carousel.carousel_upload_to, verbose_name='케러셀 이미지')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='제목')),
                ('content', models.TextField(blank=True, verbose_name='내용')),
                ('ordering', models.IntegerField(default=0, help_text='작을수록 우선 출력', verbose_name='정렬 순서')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '캐러셀 이미지',
                'verbose_name_plural': '캐러셀 이미지',
            },
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('ordering', models.IntegerField(default=0, help_text='작을수록 우선 출력', verbose_name='정렬 순서')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-ordering'],
                'verbose_name': '본당소개',
                'verbose_name_plural': '본당소개',
            },
        ),
        migrations.CreateModel(
            name='FatherSister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('MAINFATHER', '주임 신부님'), ('SECONDFATHER', '보좌 신부님'), ('BIGNUN', '원장 수녀님'), ('LITTLENUN', '전교 수녀님')], max_length=12, verbose_name='직책')),
                ('name', models.CharField(max_length=15, verbose_name='이름')),
                ('appoint_date', models.DateField(verbose_name='부임일')),
                ('holy_day', models.DateField(verbose_name='축일')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=information.models.father_sister.photo_upload_to, verbose_name='사진')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '신부님/수녀님',
                'verbose_name_plural': '신부님/수녀님',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(verbose_name='기간 시작일')),
                ('end', models.DateField(blank=True, null=True, verbose_name='기간 종료일')),
                ('event_name', models.CharField(max_length=100, verbose_name='행사명')),
                ('content', models.TextField(blank=True, verbose_name='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '연혁',
                'verbose_name_plural': '연혁',
            },
        ),
        migrations.CreateModel(
            name='Introduce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shorten', models.TextField(verbose_name='약사')),
                ('church_image', models.ImageField(blank=True, null=True, upload_to=information.models.church_introduce.introduce_upload_to, verbose_name='본당 이미지')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '본당소개',
                'verbose_name_plural': '본당소개',
            },
        ),
        migrations.CreateModel(
            name='PastoralOrientation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='제목')),
                ('content', models.TextField(blank=True, verbose_name='내용')),
                ('image', models.ImageField(blank=True, null=True, upload_to=information.models.pastoral_orientation.pastoral_orientation_upload_to, verbose_name='이미지')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '사목지향',
                'verbose_name_plural': '사목지향',
            },
        ),
        migrations.CreateModel(
            name='Popup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popup_width', models.PositiveIntegerField(default=350, help_text='px단위입니다.', verbose_name='팝업창 가로 사이즈')),
                ('popup_height', models.PositiveIntegerField(default=450, help_text='px단위입니다.', verbose_name='팝업창 세로 사이즈')),
                ('popup_top', models.PositiveIntegerField(default=0, help_text='px단위입니다.', verbose_name='팝업창 위치 위에서')),
                ('popup_left', models.PositiveIntegerField(default=0, help_text='px단위입니다.', verbose_name='팝업창 위치 좌측에서')),
                ('popup_image', models.ImageField(upload_to=information.models.popup.popup_image_upload_to, verbose_name='팝업창 이미지')),
                ('start_date', models.DateTimeField(verbose_name='팝업창 시작일')),
                ('end_date', models.DateTimeField(verbose_name='팝업창 만료일')),
                ('is_scroll', models.BooleanField(verbose_name='스크롤 유무')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '팝업',
                'verbose_name_plural': '팝업',
            },
        ),
        migrations.AddField(
            model_name='condition',
            name='introduce',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information.Introduce', verbose_name='개황'),
        ),
    ]
