# Generated by Django 2.0.7 on 2022-07-04 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='content',
            field=models.TextField(default='content', verbose_name='내용'),
            preserve_default=False,
        ),
    ]
