# Generated by Django 2.0.7 on 2022-07-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0002_condition_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='content',
            field=models.CharField(max_length=100, verbose_name='내용'),
        ),
    ]
