# Generated by Django 2.0.7 on 2022-07-04 14:20

from django.db import migrations, models
import information.models.popup


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0003_auto_20220704_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='popup',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='popup',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='popup',
            name='popup_content',
            field=models.TextField(blank=True, verbose_name='팝업창 내용'),
        ),
        migrations.AddField(
            model_name='popup',
            name='popup_title',
            field=models.CharField(blank=True, max_length=100, verbose_name='팝업창 제목'),
        ),
        migrations.AlterField(
            model_name='popup',
            name='popup_image',
            field=models.ImageField(blank=True, null=True, upload_to=information.models.popup.popup_image_upload_to, verbose_name='팝업창 이미지'),
        ),
    ]
