# Generated by Django 2.0.7 on 2022-08-01 07:06

from django.db import migrations, models
import information.models.carousel


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0004_auto_20220704_2320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='popup',
            name='popup_image',
        ),
        migrations.AddField(
            model_name='popup',
            name='is_center',
            field=models.BooleanField(default=False, verbose_name='팝업창 위치 중앙배치 유무'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carousel',
            name='carousel_image',
            field=models.ImageField(upload_to=information.models.carousel.carousel_upload_to, verbose_name='케러셀 이미지'),
        ),
        migrations.AlterField(
            model_name='popup',
            name='popup_content',
            field=models.TextField(verbose_name='팝업창 내용'),
        ),
        migrations.AlterField(
            model_name='popup',
            name='popup_height',
            field=models.PositiveIntegerField(default=500, help_text='px단위입니다.', verbose_name='팝업창 세로 사이즈'),
        ),
        migrations.AlterField(
            model_name='popup',
            name='popup_left',
            field=models.PositiveIntegerField(default=0, help_text='%단위입니다.', verbose_name='팝업창 위치 좌측에서'),
        ),
        migrations.AlterField(
            model_name='popup',
            name='popup_top',
            field=models.PositiveIntegerField(default=0, help_text='%단위입니다.', verbose_name='팝업창 위치 위에서'),
        ),
        migrations.AlterField(
            model_name='popup',
            name='popup_width',
            field=models.PositiveIntegerField(default=400, help_text='px단위입니다.', verbose_name='팝업창 가로 사이즈'),
        ),
    ]
