# Generated by Django 2.0.7 on 2020-11-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_uploadfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='upload_file',
            field=models.FileField(blank=True, null=True, upload_to='video/upload-file'),
        ),
    ]
